name: CI

on:
  pull_request:

  push:
    branches: [master, 0.1x]

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Rubocop
      run: |
        gem install bundler
        bundle config set without 'development test'
        bundle config set with 'lint'
        bundle install
        bundle exec rubocop --format progress

    - name: Yard-Junk
      run: |
        gem install yard-junk --no-document
        yard-junk --path lib

  build:
    needs: [linting]
    runs-on: ubuntu-latest
    name: build ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.4', '2.5', '2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev

    - name: Build
      run: |
        gem install bundler -v '<2'
        bundle install --jobs 4 --retry 3

    - name: Setup Code Climate
      if: matrix.ruby == '2.6'
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Test
      continue-on-error: ${{ matrix.experimental }}
      run: bundle exec rake

    - name: Run Code Climate Test Reporter
      if: success() && matrix.ruby == '2.6'
      run: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
      continue-on-error: true
